all:
	git clone https://github.com/deanturpin/audio
	git clone https://github.com/deanturpin/dev
	git clone https://github.com/deanturpin/handt
	git clone https://github.com/deanturpin/dft

check:
	check-commits
