#!/bin/bash

[[ $# == 0 ]] && echo "Usage: $0 <file to watch>" && exit -1

echo Wait for $1
readonly flags='-std=c++17 --all-warnings --extra-warnings -pedantic-errors -Wshadow -Wfloat-equal -Weffc++ -Wdelete-non-virtual-dtor -lstdc++fs -fopenmp'

base=${1%.*}

while :; do
	
	inotifywait -qe modify $base.cpp
	clear

	echo Compiling
	time clang++-6.0 -o $base.o $base.cpp $flags && echo Running && time ./$base.o
done
